//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2019.10.22 at 02:14:28 PM CEST 
//


package dev.sgora.xml_editor.model.xml;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;
import java.math.BigDecimal;


/**
 * <p>Java class for accountCredit complex type.
 *
 * <p>The following schema fragment specifies the expected content contained within this class.
 *
 * <pre>
 * &lt;complexType name="accountCredit">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="limit" type="{}positiveTwoPlaceDecimal"/>
 *         &lt;element name="interest" type="{}positiveTwoPlaceDecimal"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "accountCredit", propOrder = {
		"limit",
		"interest"
})
public class AccountCredit {

	@XmlElement(required = true)
	protected BigDecimal limit;
	@XmlElement(required = true)
	protected BigDecimal interest;

	/**
	 * Gets the value of the limit property.
	 *
	 * @return possible object is
	 * {@link BigDecimal }
	 */
	public BigDecimal getLimit() {
		return limit;
	}

	/**
	 * Sets the value of the limit property.
	 *
	 * @param value allowed object is
	 *              {@link BigDecimal }
	 */
	public void setLimit(BigDecimal value) {
		this.limit = value;
	}

	/**
	 * Gets the value of the interest property.
	 *
	 * @return possible object is
	 * {@link BigDecimal }
	 */
	public BigDecimal getInterest() {
		return interest;
	}

	/**
	 * Sets the value of the interest property.
	 *
	 * @param value allowed object is
	 *              {@link BigDecimal }
	 */
	public void setInterest(BigDecimal value) {
		this.interest = value;
	}

}
