//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2019.10.18 at 07:10:47 PM CEST 
//


package dev.sgora.xml_editor.model;




/**
 * <p>Java class for companyType.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * <p>
 * <pre>
 * &lt;simpleType name="companyType">
 *   &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *     &lt;enumeration value="S.A."/>
 *     &lt;enumeration value="s. c."/>
 *     &lt;enumeration value="sp. j."/>
 *     &lt;enumeration value="sp. k."/>
 *     &lt;enumeration value="sp. p."/>
 *     &lt;enumeration value="sp. z o.o."/>
 *   &lt;/restriction>
 * &lt;/simpleType>
 * </pre>
 * 
 */
public enum CompanyType {

    S_A("S.A."),
    S_C("s. c."),
    SP_J("sp. j."),
    SP_K("sp. k."),
    SP_P("sp. p."),
    SP_Z_O_O("sp. z o.o.");
    private final String value;

    CompanyType(String v) {
        value = v;
    }

    public String value() {
        return value;
    }

    public static CompanyType fromValue(String v) {
        for (CompanyType c: CompanyType.values()) {
            if (c.value.equals(v)) {
                return c;
            }
        }
        throw new IllegalArgumentException(v);
    }

}
