//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2019.10.18 at 07:10:47 PM CEST 
//


package dev.sgora.xml_editor.model;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for accountStatement complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="accountStatement">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;all>
 *         &lt;element name="bank" type="{}company"/>
 *         &lt;element name="client" type="{}person"/>
 *         &lt;element name="account" type="{}account"/>
 *         &lt;element name="period" type="{}statementPeriod"/>
 *         &lt;element name="transactionHistory" type="{}transactionHistory"/>
 *       &lt;/all>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "accountStatement", propOrder = {

})
public class AccountStatement {

    @XmlElement(required = true)
    protected Company bank;
    @XmlElement(required = true)
    protected Person client;
    @XmlElement(required = true)
    protected Account account;
    @XmlElement(required = true)
    protected StatementPeriod period;
    @XmlElement(required = true)
    protected TransactionHistory transactionHistory;

    /**
     * Gets the value of the bank property.
     * 
     * @return
     *     possible object is
     *     {@link Company }
     *     
     */
    public Company getBank() {
        return bank;
    }

    /**
     * Sets the value of the bank property.
     * 
     * @param value
     *     allowed object is
     *     {@link Company }
     *     
     */
    public void setBank(Company value) {
        this.bank = value;
    }

    /**
     * Gets the value of the client property.
     * 
     * @return
     *     possible object is
     *     {@link Person }
     *     
     */
    public Person getClient() {
        return client;
    }

    /**
     * Sets the value of the client property.
     * 
     * @param value
     *     allowed object is
     *     {@link Person }
     *     
     */
    public void setClient(Person value) {
        this.client = value;
    }

    /**
     * Gets the value of the account property.
     * 
     * @return
     *     possible object is
     *     {@link Account }
     *     
     */
    public Account getAccount() {
        return account;
    }

    /**
     * Sets the value of the account property.
     * 
     * @param value
     *     allowed object is
     *     {@link Account }
     *     
     */
    public void setAccount(Account value) {
        this.account = value;
    }

    /**
     * Gets the value of the period property.
     * 
     * @return
     *     possible object is
     *     {@link StatementPeriod }
     *     
     */
    public StatementPeriod getPeriod() {
        return period;
    }

    /**
     * Sets the value of the period property.
     * 
     * @param value
     *     allowed object is
     *     {@link StatementPeriod }
     *     
     */
    public void setPeriod(StatementPeriod value) {
        this.period = value;
    }

    /**
     * Gets the value of the transactionHistory property.
     * 
     * @return
     *     possible object is
     *     {@link TransactionHistory }
     *     
     */
    public TransactionHistory getTransactionHistory() {
        return transactionHistory;
    }

    /**
     * Sets the value of the transactionHistory property.
     * 
     * @param value
     *     allowed object is
     *     {@link TransactionHistory }
     *     
     */
    public void setTransactionHistory(TransactionHistory value) {
        this.transactionHistory = value;
    }

}
