//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2019.10.22 at 02:14:28 PM CEST 
//


package dev.sgora.xml_editor.model;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for person complex type.
 *
 * <p>The following schema fragment specifies the expected content contained within this class.
 *
 * <pre>
 * &lt;complexType name="person">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="name" type="{}fullName"/>
 *         &lt;element name="address" type="{}address"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "person", propOrder = {
		"name",
		"address"
})
public class Person {

	@XmlElement(required = true)
	protected FullName name;
	@XmlElement(required = true)
	protected Address address;

	/**
	 * Gets the value of the name property.
	 *
	 * @return possible object is
	 * {@link FullName }
	 */
	public FullName getName() {
		return name;
	}

	/**
	 * Sets the value of the name property.
	 *
	 * @param value allowed object is
	 *              {@link FullName }
	 */
	public void setName(FullName value) {
		this.name = value;
	}

	/**
	 * Gets the value of the address property.
	 *
	 * @return possible object is
	 * {@link Address }
	 */
	public Address getAddress() {
		return address;
	}

	/**
	 * Sets the value of the address property.
	 *
	 * @param value allowed object is
	 *              {@link Address }
	 */
	public void setAddress(Address value) {
		this.address = value;
	}

}
